### ISSUE TITLE
Kompilliertes PDF hochladen?

### ISSUE THREAD

**Issue by emanuelduss** [luxeria/luxstat#1]
Macht es Sinn, das kompillierte PDF hochzuladen? Das sind ja eigentlich Binärdaten und bei jeder Änderung ändert sich sehr viel im PDF.

Für mich macht es keinen Sinn. Kompillierte & ausführbare Programme werden ja auch nicht hochgeladen. Man könnte dann `luxstat.pdf` in die `.gitignore` aufnehmen.

**Comment by daniw** [comment]
Das PDF sollte aus dem Repo entfernt werden. 

Es können ja releases erstellt und die PDFs dort angehängt werden. 

Für Änderungsvorschläge könnte man ja einen pre-release erstellen.

**Comment by ninux** [comment]
Ich schliesse mich dem an, dass die PDF's mit der Release-Funktion von GitHub verwaltet werden. 

Im LuXeria wurde mal vereinbart, dass der aktuelle Release auf dem Wiki liegt. Demzufolge müssten wir hier nicht zwingend Releases haben.

**Comment by gandro** [comment]
Beispiel https://github.com/luxeria/latex-basics

**Comment by gandro** [comment]
Fixed via #9 - die PDFs aus dem Standard-Branch befinden sich in den GitHub Actions Artefakten.
